Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
out.path <- "d:/temp/out/";   # where files will be written
git.path <- "d:/gitFiles/";   # local git directory for input template

sub.ids <- c("1111", "2222", "3333");  # subject IDs to run

# check if out.path exists, and make it if not.
if (!dir.exists(out.path)) { dir.create(out.path); }

in.file <- readLines(paste0(git.path, "template_ERfilmTask.rnw"));   # read in the template knitr
for (sub.id in sub.ids) {    # sub.id <- sub.ids[1];
  s.path <- paste0(out.path, sub.id, "/");   # make a subdirectory of out.path for each person
  if (!dir.exists(s.path)) { dir.create(s.path); }
  
  out.file <- gsub('do.sub <- "9999";', paste0('do.sub <- "', sub.id, '";'), in.file);    # put in subject ID
  cat(out.file, file=paste0(s.path, sub.id, "_ERfilmTask.rnw"), sep="\n");    # write out the knitr template with this person's info
}
------------------

Error in file(con, "r"): cannot open the connection
Traceback:

1. readLines(paste0(git.path, "template_ERfilmTask.rnw"))
2. file(con, "r")
ERROR: Error in file(con, "r"): cannot open the connection


